### PR TITLE
add several id and name fields

### PR DESCRIPTION
**Pull request by rwang-lyra**
## Story
https://lyrahealth.atlassian.net/browse/DATA-1330

## Description
Adding these fields to the following tables.

NETSUITE2__BALANCE_SHEET
- accounting_book_id
- subsidiary_id
- subsidiary_name
- 
NETSUITE2__INCOME_STATEMENT
- accounting_book_id

NETSUITE2__TRANSACTION_DETAILS
- accounting_book_id
- subsidiary_id

### CODE REVIEW

**Comment by jmongerlyra** [comment]
@rwang-lyra Can you merge the translation rate fix branch into this branch? Then I can check the table balances.

**Comment by rwang-lyra** [comment]
> @rwang-lyra Can you merge the translation rate fix branch into this branch? Then I can check the table balances.
@jmongerlyra  I want to keep the commits atomic/single responsibility so it could be easily reviewed merged back to fivetran's eventually, if that makes sense

**Comment by rwang-lyra** [comment]
> > @rwang-lyra Can you merge the translation rate fix branch into this branch? Then I can check the table balances.
> > @jmongerlyra  I want to keep the commits atomic/single responsibility so it could be easily reviewed merged back to fivetran's eventually, if that makes sense

perhaps i can merge this in first

**Comment by rwang-lyra** [comment]
> @rwang-lyra Can you merge the translation rate fix branch into this branch? Then I can check the table balances.

i've updated fix/translation_rate branch which has both commits, you can pull and test with it now

**Pull request merged**
